[[redirects]]
  from = "/services/*"
  to = "https://power-customer-6271-dev-ed.scratch.my.salesforce-sites.com/services/:splat"
  status = 200
  force = true
  headers = [
  # {"Access-Control-Allow-Origin" = "*"},
     #  {"Access-Control-Allow-Methods" = "POST, OPTIONS"},
     #  {"Access-Control-Allow-Headers" = "Content-Type, Authorization"}
  ]
